
workflows:
  ios-build:
    name: iOS Build
    instance_type: mac_mini_m2
    environment:
      xcode: latest
    scripts:
      - name: Build project
        script: |
          xcodebuild -project TestApp.xcodeproj \
                     -scheme TestApp \
                     -sdk iphoneos \
                     -configuration Release \
                     -archivePath $CM_BUILD_DIR/build/TestApp.xcarchive \
                     archive
      - name: Export IPA
        script: |
          xcodebuild -exportArchive \
                     -archivePath $CM_BUILD_DIR/build/TestApp.xcarchive \
                     -exportOptionsPlist ExportOptions.plist \
                     -exportPath $CM_BUILD_DIR/build/ipa
    artifacts:
      - build/ipa/*.ipa
